# CI Build Workflow
name: CI Build

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "doc/*"
      - "*.md"
      - "imgs/*"
      - "app/src/assets/**"
      - "crowdin.yml"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_app:
    runs-on: macos-latest
    name: Build App
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-overwrite-existing: true

      - name: Setup Env
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          echo "GIT_ACTOR=${{ secrets.GIT_ACTOR }}" >> $GITHUB_ENV
          echo "GIT_TOKEN=${{ secrets.GIT_TOKEN }}" >> $GITHUB_ENV

      - name: Build with Gradle (Canary)
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          ./gradlew assembleDebug --stacktrace --refresh-dependencies
          echo "IS_DEBUG=true" >> $GITHUB_ENV

      - name: Build with Gradle (Debug)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          ./gradlew assembleDebug --stacktrace --refresh-dependencies
          echo "IS_DEBUG=true" >> $GITHUB_ENV

      - name: Upload Build Reports on Failure
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: build-reports
          path: '**/build/reports/'

      - name: Find APKs
        run: |
          if [ "${{ env.IS_DEBUG }}" = "true" ]; then
            APK_FILE=$(find app/build/outputs/apk/debug -name '*.apk' | head -n 1)
          else
            APK_FILE=$(find app/build/outputs/apk/canary -name '*.apk' | head -n 1)
          fi
          echo "APK_FILE=$APK_FILE" >> $GITHUB_ENV
          echo "APK_FILE_NAME=$(basename "$APK_FILE" .apk)" >> $GITHUB_ENV

      - name: Show APKs SHA256
        if: success()
        run: |
          echo "### Build Success" >> $GITHUB_STEP_SUMMARY
          echo "|Artifact|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:---:|:---|" >> $GITHUB_STEP_SUMMARY
          APK_SHA256=($(shasum -a 256 "${{ env.APK_FILE }}"))
          if [ "${{ env.IS_DEBUG }}" = "true" ]; then
            echo "|Debug|$APK_SHA256" >> $GITHUB_STEP_SUMMARY
          else
            echo "|Canary|$APK_SHA256" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload APKs
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APK_FILE_NAME }}
          path: ${{ env.APK_FILE }}
          compression-level: 9


